deployment:
  tasks:
    - export DEPLOYPATH=/home/ifthesel/staging/
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp -R data $DEPLOYPATH
    - /bin/cp -R css $DEPLOYPATH
    - /bin/cp -R js $DEPLOYPATH
    - /bin/cp -R assets $DEPLOYPATH
